version: '3.5'

services:

  crm_frontend_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crm_frontend_dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: 
     - .env
    volumes:
      - .:/app
      - /app/node_modules
  crm_frontend_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: crm_frontend_prod
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file: 
     - .env
  